#parametrise function without return type
def arthmaticoperation(num1,num2) :
    num1=10
    num2=2
    sum=num1+num2
    print(f"sum is:-{sum}")
    multi=num1*num2
    print(f"multiplication is:-{multi}")
    div=num1/num2
    print(f"div is:-{div}")
    
arthmaticoperation(30,15)

#function with return type with parameters
def addition(a,b):
    c=a+b
    return c
#w will store value of c
w=addition(4,562)
print(w)





